### ISSUE TITLE
Prefixes on convert -> deconvert a citation

### ISSUE THREAD

**Issue by iandol** [teertinker/JabRef_LibreOffice_Converter#3]
If I have a citation `\cite{doe2022}` and I convert it to a Reference field and then back I get `\cite{100_1_does2022}`. For workflows where we write in other tools and only use LibreOffice to make the bibliography, this `100_1_` prefix can get in the way and cause problems if we copy and paste text or move paragraphs around. Is there a reason to add this prefix to the plain text?

**Comment by teertinker** [comment]
Dear Ian,the prefix is necessary for the internal handling of Jabref, the number 100 represents a unique identifier and increases with each citations
\cite{doe2022}  ... \cite{doe2022}becomes
\cite{100_1_doe2022}  \cite{101_1_ doe2022} 


I started the counter at position 100 to circumvent problems with prior citations.
The number _1_ is also necessary for internal handling. It is used by JabRef to distinguish between: Citation, In-text Citation and empty citation. 

In plain text, you don't need the prefix. But without prefix the converter assumes you are using a standard citation.
Hope, this helps.
My workflow ist usually: Typing the manuscript with plain-text cite keys (\cite{doe2022}). And convert the whole manuscript after being finished.

**Comment by iandol** [comment]
Thanks for the information about the prefixes. I will close this, although for workflows that go back and forth between external programs and LibreOffice (say you are writing with collaborators using other apps), the prefixes can complicate the workflow a bit.
