### ISSUE TITLE
BASIC runtime error when try to run

### ISSUE THREAD

**Issue by David-Duffy** [teertinker/JabRef_LibreOffice_Converter#4]
Hi. This seemed to install correctly, but when I run it, I get stuck on Line 17
Dialogue.Libraries.LoadLibrary("JabRefConverterLib")
with NoSuchElementException
![Screenshot_2023-07-03_19-09-45](https://github.com/teertinker/JabRef_LibreOffice_Converter/assets/8063252/e7bbe441-7154-488d-836a-161518592969)
LibreOffice 7.3.7.2 on Ubuntu  22.04.2 LTS 5.15.0-76-generic 

Is it something simple?

**Comment by teertinker** [comment]
Sorry,at the moment I have no idea. I used the macro in linux and windows environment and never got this error. It seems to be unable to show the dialog window. But I have no idea why.


    On Tuesday, July 4, 2023 at 01:32:25 AM GMT+2, David-Duffy ***@***.***> wrote:  
 
 


Hi. This seemed to install correctly, but when I run it, I get stuck on Line 17
Dialogue.Libraries.LoadLibrary("JabRefConverterLib")
with NoSuchElementException

LibreOffice 7.3.7.2 on Ubuntu 22.04.2 LTS 5.15.0-76-generic

Is it something simple?

**Comment by averter** [comment]
I'm experiencing exactly the same issue in Linux Mint. Any luck solving it?

**Comment by teertinker** [comment]
Could you try the older version and report, whether it is working? https://github.com/teertinker/JabRef_LibreOffice_Converter/blob/main/old%20version%20JabRefConverter.oxt
