### ISSUE TITLE
Works great on Windows but not on Linux

### ISSUE THREAD

**Issue by ueberferret** [teertinker/JabRef_LibreOffice_Converter#5]
When I add the extension to LibreOffice 7 on Ubuntu 22.04, no button is created in the toolbar and I haven't found any other way to launch the functionality. 
Also, removing the extension from Libreoffice on Ubuntu causes an error.

**Comment by ueberferret** [comment]
Actually, on further testing, it works fine on Linux if I use an old JabRefCoverter.oxt . The issue is something with the version of the .oxt file. If I install a JabRefConverter.oxt that I downloaded in January 2021 with file size  (28,698 bytes) on the latest Libreoffice Writer under Linux, all works as it should. But if use the version downloaded just now from https://github.com/teertinker/JabRef_LibreOffice_Converter/blob/main/JabRefConverter.oxt with file size 29,559 bytes the extension fails to install correctly or to be uninstalled correctly.

**Comment by teertinker** [comment]
Thank you for reporting!
I will have a look at it soon

**Comment by teertinker** [comment]
Should be solved now.
